export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const GET_DOG_DETAILS = "GET_DOG_DETAILS";
export const CLEAN_DOG_DETAILS = "CLEAN_DOG_DETAILS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const SET_SELECTED_TEMPERAMENTS = "SET_SELECTED_TEMPERAMENTS";
export const UPDATE_SELECTED_ID_TYPE = "UPDATE_SELECTED_ID_TYPE";
export const SET_SELECTED_MODE = "SET_SELECTED_MODE";
export const GET_DB_BREEDS = "GET_DB_BREEDS";